<div class="row ">
       <?php 
        $attr = array('autocomplete' => 'off', 'onsubmit'=>'return confirm("¿Realmente quiere crear esta carta?")');
        echo form_open('cartas/alta', $attr); 
    ?>
        <div class="row">
          <div class="input-field col s4">
            <input placeholder="nombre" id="nombre" type="text" class="validate" name="nombre">
            <label for="nombre">Nombre</label>
          </div>
        </div>
        <div>
            <div class="row center-align">
                <div class="col s12">
                  <ul class="tabs">
                    <li class="tab col s3"><a class="active" href="#productos">Productos</a></li>
                    <li class="tab col s3"><a href="#horas">Establecer Horas</a></li>
                    <li class="tab col s3"><a href="#dias">Establecer Días</a></li>
                  </ul>
                </div>
                <div id="horas" class="col s12 center-align">
                    <table>
                        <tbody>
                            <td><?php for($i=0;$i<8;$i++){ ?>
                                <input id="hora<?php echo $i?>" type="checkbox" name="horas[]" value="<?php echo $i?>" >
                                    <label for="hora<?php echo $i?>">Hora: <?php echo $i.':00' ?></label><br>    
                                <?php }?>
                            </td>
                            <td><?php for($i=8;$i<16;$i++){ ?>
                                    <input id="hora<?php echo $i?>" type="checkbox" name="horas[]" value="<?php echo $i?>" >
                                    <label for="hora<?php echo $i?>">Hora: <?php echo $i.':00' ?></label><br>    
                                <?php }?>
                            </td>
                            <td><?php for($i=16;$i<24;$i++){ ?>
                                    <input id="hora<?php echo $i?>" type="checkbox" name="horas[]" value="<?php echo $i?>" >
                                    <label for="hora<?php echo $i?>">Hora: <?php echo $i.':00' ?></label><br>    
                                <?php }?>
                            </td>
                          </tbody>
                    </table>
                </div>
                <div id="dias" class="col s12 left-align">
                    <input id="lun" type="checkbox" name="dias[]" value="0" >
                    <label for="lun">Lunes</label><br>
                    <input id="mar" type="checkbox" name="dias[]" value="1">
                    <label for="mar">Martes</label><br>
                    <input id="mie" type="checkbox" name="dias[]" value="2">
                    <label for="mie">Miercoles</label><br>
                    <input id="jue" type="checkbox" name="dias[]" value="3">
                    <label for="jue">jueves</label><br>
                    <input id="vie" type="checkbox" name="dias[]" value="4">
                    <label for="vie">Viernes</label><br>
                    <input id="sab" type="checkbox" name="dias[]" value="5">
                    <label for="sab">Sabado</label><br>
                    <input id="dom" type="checkbox" name="dias[]" value="6">
                    <label for="dom">Domingo</label>
                </div>
                <div id="productos" class="col s12 left-align">
                    <table class="responsive-table striped "> 
                        <tbody>
                        <?php foreach ($productos as $producto) {?>
                            <tr><td> <input id="<?php echo $producto['nombre'] ?>" type="checkbox" name="productos[]" value="<?php echo $producto['id'] ?>" >
                             <label for="<?php echo $producto['nombre'] ?>"><?php echo $producto['nombre'] ?></label><br>
                            </td></tr>
                        <?php } ?>
                        </tbody>
                    </table>
                </div>
                
                <button type="submit" class="btn waves-effect waves-light tooltipped" data-position="bottom" data-delay="50" data-tooltip="Lista de Precios">
                        Siguiente
                </button>
                </a>
                <a href ="<?php echo  site_url()?>cartas/" class="btn waves-effect waves-light">Salir</a>
                 
            </div>
        </div>
    </form>
</div>