<div class="txt-cabecera">
    PRODUCTOS.
</div>
<div class="txt-info">
    ..: Listado de productos :..
</div>
<div class="row center-align">
    <a class="btn waves-effect waves-green" href="<?php echo site_url()."productos/alta"?>">AGREGAR PRODUCTO</a>
</div>
<div class="row">
    <div class="col m8 s12 offset-m2">
        <table class="responsive-table">
            <thead>
                <tr>
                    <th>#ID</th>
                    <th>Imagen</th>
                    <th>Nombre</th>
                    <th>Editar..</th>
                    <th>Eliminar..</th>
                </tr>
            </thead>
            <tbody id="tablaProductos">   
            <?php
                foreach( $productos as $row ){
                    $id = $row['id'];
                    $np = $row['nombre'];
            ?>
                <tr id="<?php echo 'fp'.$id; ?>">
                    <td><?php echo $id; ?></td>
                    <td><?php echo 'Imagen'; ?></td>
                    <td><?php echo $np; ?></td>
                    <td> 
                        <a class="btn waves-effect waves-green" href="<?php echo site_url()."productos/editar/".$id?>">
                            <i class="material-icons">edit</i>
                        </a>
                    </td>
                    <td>
                        <a class="dropdown-button btn" data-activates='<?php echo 'drop'.$id; ?>'>
                            <i class="material-icons">delete</i>
                        </a>
                        <!-- Dropdown Structure -->
                        <ul id='<?php echo 'drop'.$id; ?>' class='dropdown-content'>
                            <li>¿Confirma?</li>
                            <li class="divider"></li>
                            <li>
                                <a onClick="<?php echo "productos.eliminar(".$id.")"; ?>">Sí</a>
                            </li>
                            <li>
                                <a>No</a>
                            </li>
                        </ul>
                    </td>
                </tr>
            <?php
                }
            ?>
            </tbody>
        </table>
    </div>
</div>
<div class="row center-align">
    <a class="btn waves-effect waves-light tooltipped" data-tooltip="Volver a roles" href="<?php echo site_url()?>intranet">Volver</a> 
</div>