<div class="txt-cabecera">
    LISTAS DE PRECIO.
</div>
<div class="txt-info">
    ..: Listando listas de precio :..
</div>

<div class="row center-align">
    <a class="btn waves-effect waves-green" onClick="listaprecios.preAlta()" >AGREGAR LISTA</a>
</div>
<div class="row">
    <div class="col m8 s12 offset-m2">
        <table class="responsive-table">
            <thead>
                <tr>
                    <th>#ID</th>
                    <th>Nombre</th>
                    <th>Modificada el</th>
                    <th>Creador</th>
                    <th>Ver</th>
                    <th>Editar..</th>
                    <th>Eliminar..</th>
                </tr>
            </thead>
            <tbody id="tblListaPrecios">   
            <?php
                foreach( $listas as $row ){
                    $id = $row['id'];
                    $nm = $row['nombre'];
                    $um = $row['fecha_modificacion'];
                    $nc = $row['creador'];
            ?>
                <tr id="<?php echo 'flp'.$id; ?>">
                    <td><?php echo $id; ?></td>
                    <td><?php echo $nm; ?></td>
                    <td><?php echo $um; ?></td>
                    <td><?php echo $nc; ?></td>
                    <td> 
                        <a class="btn waves-effect waves-green"  href="<?php echo site_url()."listaprecios/ver/".$id; ?>">
                            <i class="material-icons">info</i>
                        </a>
                    </td>
                    <td>
                        <a class="btn waves-effect waves-green"  href="<?php echo site_url()."listaprecios/editar/".$id; ?>">
                            <i class="material-icons">edit</i>
                        </a>
                    </td>
                    <td>
                        <a class='dropdown-button btn' data-activates='<?php echo 'drop'.$id; ?>'>
                            <i class="material-icons">delete</i>
                        </a>
                        <!-- Dropdown Structure -->
                        <ul id='<?php echo 'drop'.$id; ?>' class='dropdown-content'>
                            <li>¿Confirma?</li>
                            <li class="divider"></li>
                            <li>
                                <a onClick="<?php echo "listaprecios.eliminar(".$id.")"; ?>">Sí</a>
                            </li>
                            <li>
                                <a>No</a>
                            </li>
                        </ul>
                    </td>
                </tr>
            <?php
                }
            ?>
            </tbody>
        </table>
    </div>
</div>

<div id="altaListaPrecios" class="modal">
    <div class="modal-content">
        <div clas="row">
            <div class="txt-info">
                Alta de lista de precios
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12 m8 offset-m2">
                <input id="nombreLista" placeholder="Ingrese nombre..." type="text">
                <label>Nombre</label>
            </div>
        </div>
        <div class="row center-align">
            <a class="btn" onClick="listaprecios.postAlta()">Confirmar</a>
        </div>
    </div>
</div>
<div class="row center-align">
    <a class="btn waves-effect waves-light tooltipped" data-tooltip="Volver a roles" href="<?php echo site_url()?>intranet">Volver</a> 
</div>