<div id="Mozo">
    <div class="col s12 center-align">
        <div  class = "div-btn-rol col s4 m3">
            <a href="<?php echo site_url() ?>webresto/empleados/abrirmesa" class="btn-rol btn-floating waves-effect waves-light">
               Abrir Mesa
                <img  src="<?php echo site_url()?>img/1.png">
            </a>
        </div>
        <div class = "div-btn-rol col s4 m3">
            <a href="<?php echo site_url() ?>webresto/empleados/mesas" class="btn-rol btn-floating waves-effect waves-light">
            Mesas
            <img src="<?php echo site_url()?>img/1.png">
            </a>
        </div>
        <div class = "div-btn-rol col s4 m3">
            <a href="<?php echo site_url() ?>webresto/empleados/menu "class="btn-rol btn-floating waves-effect waves-light">
            Menu
            <img src="<?php echo site_url()?>img/2.png">
            </a>
        </div>
        <div class = "div-btn-rol col s4 m3">
            <a href="<?php echo site_url() ?>webresto/empleados/notificaciones " class="btn-rol btn-floating waves-effect waves-light">
            Notificaciones
            <img src="<?php echo site_url()?>img/3.png">
            </a>
        </div>
        <div class = "div-btn-rol col s4 m3">
             <a href="<?php echo site_url() ?>webresto/ " class="btn-rol btn-floating waves-effect waves-light">
            Salir
            <img src="<?php echo site_url()?>img/4.png">
                    </a>
        </div>   
    </div>
</div>