<div class="row center-align">
    
    <!-- Inicio Tabs -->
        <div class="col s3">
            <table class = "striped responsive-table">
                <h4>Pendientes</h4>
                <thead>
                    
                    <th>Pedidos</th>
                </thead>
                <tbody id="pedPend">
                </tbody>
            </table>
        </div>
        <div class="col s3">
            <h4> </h4>
            <table class = "striped responsive-table">
                <thead>
                    <th >Promociones</th>
                </thead>
                <tbody id="promoPend">
                </tbody>
            </table>
        </div>
   
        <div class="col s3">
            <table class = "striped responsive-table ">
                <h4>Procesados</h4>
                <thead>
                    <th >Pedidos</th>
                </thead>
                <tbody id="pedProc">
                </tbody>
            </table>
        </div>
        <div class="col s3">
            <h4> </h4>
            <table class = "striped responsive-table">
                <thead>
                    <th >Promociones</th>
                </thead>
                <tbody id="promoProc">
                </tbody>
            </table>
        </div>
  
      <!-- Fin Tabs -->
    <div class="col s12">
        <a href ="<?php echo  site_url()?>webresto/" class="btn waves-effect waves-light">Volver</a>
    </div>
</div>   


    
