<div class="col s12 l12">
    <p class="center-align">
        Esto es un parrafo de bienvinida a webresto 2.0
        Hay que trabajar para escribir un liundo texto.
        Salhdos cordiales.
        Fede
    </p>
</div>
<div class="row">
    <div class="col l8 s12">
        <div>
            <a class="btn-login btn-floating waves-effect waves-light">
                <img src="http://th01.deviantart.net/fs70/PRE/i/2013/126/1/e/nature_portrait_by_pw_fotografie-d63tx0n.jpg">
            </a>
            <a class="btn-login btn-floating waves-effect waves-light">
                <img src="http://th01.deviantart.net/fs70/PRE/i/2013/126/1/e/nature_portrait_by_pw_fotografie-d63tx0n.jpg">
            </a>
        </div>
        <div class="panel-login">
            <label>Usuario</label> 
            <label>Contraseña</label>
            <a id="btn-atras-login" class="btn-large btn-floating waves-effect waves-light">
                Atras
            </a>
        </div>
</div>    
</div>