<div class="row">
    <div class="col s12 center-align">
        <p>
            Bienvenidos a WebResto 2.0. Acceda a nuestra plataforma y comience a tramitar todos sus pedidos.
        </p>
    </div>
</div>

<div class="row">
    <div class="col s12 center-align">
        <div class="row">
            <a id="btn-login-empleados" >
                <img class="btn-login btn-floating waves-effect waves-light" src="img/empleados.png">
            </a>
            <a id="btn-login-usuarios" >
                <img class="btn-login btn-floating waves-effect waves-light" src="img/clientes.png">
            </a>   
        </div>
    </div>
</div>

<?php if ($hayError){ ?>
<div class="col s12 center-align">
    <label class="errorLogin">
        <?php echo $error; ?>
    </label>
</div>
<?php } ?>

<div id="pnl-opc-login-usuarios" class="row panel-login">
    <div class="col s12 center-align">
        <div class="row">
            <a href="<?php echo site_url() ?>webresto/loginFacebook">
                <img class="btn-floating waves-effect waves-light" src="img/fb.png">
            </a>
            <a href="<?php echo site_url() ?>webresto/loginGMail">
                <img class="btn-floating waves-effect waves-light" src="img/g+.png">
            </a> 
            <a id="btn-login-usuarios-local"> 
                <img class="btn-floating waves-effect waves-light" src="img/user.png">
            </a>  
        </div> 
    </div>
</div>

<div id="pnl-login-empleados" class="row panel-login center-align">
    <form class="col s8 m4 offset-s2 offset-m4" action="<?php echo site_url() ?>webresto/loginEmpleado" method="post">
        <div class="row">
            <div class="input-field col s12">
              <input id="NE" name="empleado_name" type="text" class="validate">
              <label for="NE">Usuario</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <input id="EP" name="empleado_password" type="password" class="validate">
                <label for="EP">Password</label>
            </div>
        </div>
        <button class="btn waves-effect waves-light" type="submit" name="action">
            Ingresar <i class="material-icons right">send</i>
        </button>
    </form>
</div>

<div id="pnl-login-usuarios" class="row panel-login">
    <form class="col s8 m4 offset-s2 offset-m4" action="<?php echo site_url() ?>webresto/loginCliente" method="post">
        <div class="row">
            <div class="input-field col s12">
              <input id="CN" name="cliente_name" type="text" class="validate">
              <label for="CN">Usuario</label>
            </div>
        </div>
        <button class="btn waves-effect waves-light" type="submit" name="action">
            Ingresar <i class="material-icons right">send</i>
        </button>
    </form>
</div>