<div id="Cajero">
      <div class="col s12 center-align">
        <div class = "div-btn-opc col s4 m3">
            <a href="<?php echo site_url() ?>webresto/empleados/facturacion " >
            Facturacion
            <img src="<?php echo site_url()?>img/3.png" class="btn-opc btn-floating waves-effect waves-light">
            </a>
        </div>
        <div class = "div-btn-opc col s4 m3">
            <a href="<?php echo site_url() ?>webresto/empleados/notificaciones ">
            Notificaciones
            <img src="<?php echo site_url()?>img/2.png" class="btn-opc btn-floating waves-effect waves-light">
            </a>
        </div>
        <div class = "div-btn-opc col s4 m3">
          <a href="<?php echo site_url() ?>webresto/logout" >
         Salir
         <img src="<?php echo site_url()?>img/4.png" class="btn-opc btn-floating waves-effect waves-light">
                 </a>
        </div>   
    </div>
</div>