<div id="Cajero">
      <div class="col s12 center-align">
        <div class = "div-btn-rol col s4 m3">
            <a href="<?php echo site_url() ?>webresto/empleados/facturacion " class="btn-rol btn-floating waves-effect waves-light">
            Facturacion
            <img src="<?php echo site_url()?>img/3.png">
            </a>
        </div>
        <div class = "div-btn-rol col s4 m3">
            <a href="<?php echo site_url() ?>webresto/empleados/notificaciones "class="btn-rol btn-floating waves-effect waves-light">
            Notificaciones
            <img src="<?php echo site_url()?>img/2.png">
            </a>
        </div>
        <div class = "div-btn-rol col s4 m3">
          <a href="<?php echo site_url() ?>webresto/ " class="btn-rol btn-floating waves-effect waves-light">
         Salir
         <img src="<?php echo site_url()?>img/4.png">
                 </a>
        </div>   
    </div>
</div>