<div class="row txt-cabecera">
    ¡Sección en Construcción!
</div>
<div class="row txt-info">
    ..: Vista de <?php echo $funcion; ?> :..
</div>
<div class="row center-align">
    <img src="<?php echo site_url()?>img/Boton_construccion.png" class="btn-en-construccion btn-floating transparent waves-effect waves-light">
    <img src="<?php echo site_url()?>img/Boton_construccion_1.png" class="btn-en-construccion btn-floating transparent waves-effect waves-light">
    <img src="<?php echo site_url()?>img/Boton_construccion_2.png" class="btn-en-construccion btn-floating transparent waves-effect waves-light">
    
</div>
<div class="row center-align">
    <a class="boton btn-base waves-effect tooltipped" data-tooltip="Volver" href="<?php echo site_url()?>webresto" >Volver</a>
</div>
