<div class="row txt-cabecera">
    ¡SISTEMA DE PEDIDOS DE MI RESTO 2.0!
</div>
<div class="row txt-info">
    ..: Solicite la vinculación al mozo, y administre su pedido :..
</div>
<div class="row">
    <div class="col s12 center-align">
        <a class="tooltipped" data-tooltip="Info personal" href="<?php echo site_url() ?>clientes/info">
            <img src="<?php echo site_url()?>img/Boton_info_cliente.png" class="btn-opc btn-floating transparent waves-effect waves-light">
        </a>
        <a class="tooltipped" data-tooltip="Pedidos" href="<?php echo site_url() ?>clientes/pedidos">
            <img src="<?php echo site_url()?>img/Boton_menu.png" class="btn-opc btn-floating transparent waves-effect waves-light">
        </a>
        <a class="tooltipped" data-tooltip="Calificar mozo" href="<?php echo site_url() ?>clientes/calificar" >
            <img src="<?php echo site_url()?>img/Boton_calificar.png" class="btn-opc btn-floating transparent waves-effect waves-light">
        </a>
        <a class="tooltipped" data-tooltip="Cerrar session" href="<?php echo site_url() ?>clientes/logout">
            <img src="<?php echo site_url()?>img/Boton_cerrar_sesion.png" class="btn-opc btn-floating transparent waves-effect waves-light">
        </a>  
    </div>
</div>
