<div class="col s12 center-align">
    <a href="<?php echo site_url() ?>clientes/menu" >
        <img src="<?php echo site_url()?>img/1.png" class="btn-opc btn-floating waves-effect waves-light">
    </a>
    <a href="<?php echo site_url() ?>clientes/pedidos">
        <img src="<?php echo site_url()?>img/2.png" class="btn-opc btn-floating waves-effect waves-light">
    </a>
    <a href="<?php echo site_url() ?>clientes/calificar" >
        <img src="<?php echo site_url()?>img/3.png" class="btn-opc btn-floating waves-effect waves-light">
    </a>
    <a href="<?php echo site_url() ?>clientes/logout">
        <img src="<?php echo site_url()?>img/4.png" class="btn-opc btn-floating waves-effect waves-light">
    </a>  
</div>
