<div class="row txt-cabecera">
    ¡Bienvenido al sistema de pedidos de miResto!
</div>
<div class="row txt-info">
    ..: Solicite la vinculación al mozo, y administre su pedido :..
</div>
<div class="row">
    <div class="col s12 center-align">
        <a class="tooltipped" data-tooltip="Info personal" href="<?php echo site_url() ?>clientes/info">
            <img src="<?php echo site_url()?>img/1.png" class="btn-opc btn-floating waves-effect waves-light">
        </a>
        <a class="tooltipped" data-tooltip="Pedidos" href="<?php echo site_url() ?>clientes/pedidos">
            <img src="<?php echo site_url()?>img/2.png" class="btn-opc btn-floating waves-effect waves-light">
        </a>
        <a class="tooltipped" data-tooltip="Calificar mozo" href="<?php echo site_url() ?>clientes/calificar" >
            <img src="<?php echo site_url()?>img/3.png" class="btn-opc btn-floating waves-effect waves-light">
        </a>
        <a class="tooltipped" data-tooltip="Cerrar session" href="<?php echo site_url() ?>clientes/logout">
            <img src="<?php echo site_url()?>img/4.png" class="btn-opc btn-floating waves-effect waves-light">
        </a>  
    </div>
</div>
