<div class="row txt-cabecera">
    ¡SISTEMA DE PEDIDOS DE MI RESTO 2.0!
</div>
<div class="row txt-info">
    ..: Datos de vinculación :..
</div>
<div class="row">
    <div class="col s12 m8 offset-m2">
        <table class="responsive-table">
            <thead>
            <th>Nombre</th><th>ID Asignado</th><th>Mesa</th><th>Mozo</th>
            </thead>
            <tbody>
                <?php 
                    $cid = $this->session->userdata['cid'];
                    $mesa_asignada = $this->session->userdata['mesa_asignada'];
                    $cid_1 = substr($cid, 0,2);
                    $cid_2 = substr($cid, 2,2);
                    $cid_3 = substr($cid, 4,2);
                ?>
                <tr>
                    <td> <?php echo $this->session->userdata['user_name']; ?> </td>
                    <td> <?php echo $cid_1 . '-' . $cid_2 . '-' . $cid_3; ?> </td>
                    <td> <?php echo ($mesa_asignada != NULL ? $mesa_asignada['numero'] : 'Sin asignar'); ?> </td>
                    <td> <?php echo ($mesa_asignada != NULL ? $mesa_asignada['nombre_mozo'] : 'Sin asignar'); ?> </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<div class="row center-align">
    <a class="boton btn-base transparen waves-effect tooltipped" data-tooltip="Volver a webresto" href="<?php echo site_url()?>clientes/" >Volver</a>
</div>
