<div class="row txt-cabecera">
    ¡Bienvenido al sistema de pedidos de miResto!
</div>

<div class="row">
    <div class="col m8 s12 offset-m2">
        <ul class="tabs">
            <li class="tab"><a class="active" href="#menu">MENU</a></li>
            <li class="tab"><a href="#pedidos" onclick="cliente_vista.listar_carrito()">PEDIDOS</a></li>  
        </ul>
    </div>
</div>

<div id="menu" class="row">
    <div class="col m8 s12 offset-m2">
        <?php echo 'La carta actual es: '.$nombre_carta.'<br>'; ?>
        <ul class="collapsible" data-collapsible="accordion">
            <?php 
                $indice = 0;
                $cantidad = count($info_carta);
                while($indice<$cantidad){
                    $seccion_anterior = $info_carta[$indice]['nombre_seccion'];
                ?>
                    <!-- imprimo el encabezado y el tag para abrir el cuerpo del tab -->
                    <li> 
                        <div class="collapsible-header"> <?php echo $seccion_anterior; ?> </div>
                        <div class="collapsible-body">
                            <table class="responsive-table">
                            <tbody>          
                            <?php
                                //Mientras no cambie de encabezado, imprimo los elementos dentro
                                while($indice<$cantidad && $seccion_anterior === $info_carta[$indice]['nombre_seccion']){
                                    $row = $info_carta[$indice++];
                                    $np = $row['nombre_producto'];
                                    $id = $row['id_producto'];
                                    $p = $row['precio'];
                                    $id_lp = $row['id_lista_precio'];
                            ?>
                                <tr>
                                    <td> <img src="<?php echo site_url().'img/comidas/'.$id.'.png'; ?>"/> </td>
                                    <td><?php echo $np; ?></td>
                                    <td><?php echo '$'.$p; ?></td>
                                    <td> 
                                        <a class="btn waves-effect waves-green" onclick="<?php echo "cliente.producto.agregar(".$id.",'".$np."',".$p.",".$id_lp." )"; ?>"><i class="material-icons">add</i></a>
                                    </td>
                                </tr>
                            <?php
                                }
                            ?>
                            </tbody>
                            </table>
                        </div>
                    </li> 
                    
            <?php 
                }

                $indice = 0;
                $cantidad = count($info_promociones);
                while($indice<$cantidad){
                    $promo_anterior = $info_promociones[$indice]['nombre_promocion'];
                ?>
                    <li> 
                        <div class="collapsible-header"> <?php echo $promo_anterior; ?> </div>
                        <div class="collapsible-body">
                            <?php
                                $id_promo = $info_promociones[$indice]['id_promocion'];
                                $precio_promo = $info_promociones[$indice]['precio'];
                                $nom_promo = $info_promociones[$indice]['nombre_promocion'];
                            ?>
                            <div class="row">
                                <div class="input-field col s8 m1 offset-m5">
                                    <input value="<?php echo '$'.$precio_promo; ?>" type="text" readonly>
                                    <label>Costo</label>
                                </div>
                                <a class="input-field col s2 m1 btn" onclick="<?php echo "cliente.promocion.agregar(".$id_promo.",'".$nom_promo."',".$precio_promo.")"; ?>">
                                    <i class="material-icons">add</i>
                                </a>
                            </div>
                            <div class="row">
                                <table class="responsive-table">
                                <tbody>  
                                <?php
                                    //Mientras no cambie de encabezado, imprimo los elementos dentro
                                    while($indice<$cantidad && $promo_anterior === $info_promociones[$indice]['nombre_promocion']){
                                        $row = $info_promociones[$indice++];
                                        $np = $row['nombre_producto'];
                                        $id = $row['id_producto'];
                                ?>
                                    <tr>
                                        <td> <img src="<?php echo site_url().'img/comidas/'.$id.'.png'; ?>"/> </td>
                                        <td><?php echo $np; ?></td>
                                    </tr>
                                <?php
                                    }
                                ?>
                                </tbody>
                                </table>
                            </div>
                        </div>
                    </li> 
            <?php       
                }
            ?>
        </ul>
    </div>
</div>
    
<div id="pedidos" class="row">
    <div class="col m8 s12 offset-m2">
        <ul class="collapsible" data-collapsible="accordion">
            <li> 
                <div class="collapsible-header">Sin Confirmar</div>
                <div class="collapsible-body">
                    <div class="input-field col s4 m2 offset-m1 offset-s4">
                        <input id="lblTotal" type="text" value="$0.-" readonly>
                        <label>Total</label>
                    </div>
                    <div class="input-field col s12 m4 offset-m1">
                        <a class="btn waves-effect" onclick="cliente.confirmar_pedido()">Confirmar pedidos</a>
                    </div>
                    <div class="input-field col s12 m4">
                        <a class="btn waves-effect" onclick="cliente.vaciar_carrito()">Vaciar carrito</a>
                    </div>
                    <div class="row">
                        <div class="col s12 m10 offset-m1">
                            <ul class="tabs">
                                <li class="tab"><a class="active" href="#productosPen">Productos</a></li>
                                <li class="tab"><a href="#promocionesPen">Promociones</a></li>
                            </ul>
                        </div>
                    </div>
                    <div id="productosPen" class="row">
                        <table class="responsive-table">
                            <tbody id="tblCarritoProductos">  
                            </tbody>     
                        </table>
                    </div>
                    <div id="promocionesPen" class="row">
                        <table class="responsive-table">
                            <tbody id="tblCarritoPromociones">  
                            </tbody>     
                        </table>
                    </div>
                </div>
            </li>
            <li> 
                <div class="collapsible-header">Confirmados</div>
                <div class="collapsible-body">
                    <div class="row">
                        <div class="input-field col s6 m4 offset-s3 offset-m4">
                            <input id="lblTotalConfirmados" type="text" value="$0.-" readonly>
                            <label>Total acumulado</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col s12 m10 offset-m1">
                            <ul class="tabs">
                                <li class="tab"><a class="active" href="#productosProc">Productos</a></li>
                                <li class="tab"><a href="#promocionesProc">Promociones</a></li>
                            </ul>
                        </div>
                    </div>
                    <div id="productosProc" class="row">
                        <table class="responsive-table highlight">
                            <thead>
                                <tr>
                                    <th>Pedidor</th>
                                    <th>Producto</th>
                                    <th>Precio</th>
                                    <th>Estado</th>
                                </tr>
                            </thead>
                            <tbody id="tblProductosConfirmados">  
                            </tbody>     
                        </table>
                    </div>
                    <div id="promocionesProc" class="row">
                        <table class="responsive-table highlight">
                            <thead>
                                <tr>
                                    <th>Pedidor</th>
                                    <th>Producto</th>
                                    <th>Precio</th>
                                    <th>Estado</th>
                                </tr>
                            </thead>
                            <tbody id="tblPromocionesConfirmadas">  
                            </tbody>     
                        </table>
                    </div>
                </div>
            </li>
        </ul>
    </div>  
</div>


<div id="modalComentarios" class="modal">
    <div class="modal-content">
        <h4>Agregando Comentario</h4>
        <input id="inputComentario" placeholder="Sin comentarios" type="text" maxlength="85" autocomplete="off">
    </div>
    <div class="modal-footer">
        <a onClick="cliente.enviar_comentario()" class=" modal-action modal-close waves-effect waves-green btn-flat">OK</a>
    </div>
</div>

<div class="row center-align">
    <a class="btn waves-effect waves-light tooltipped" data-tooltip="Volver a webresto" href="<?php echo site_url()?>clientes/" >Volver</a>
</div>
