<div id="Gerente">
    <div class="col s12 center-align">
        <a class="btn-admin btn-floating waves-effect waves-light">
            <img src="img/1.png">
        </a>
        <a class="btn-admin btn-floating waves-effect waves-light">
            <img src="img/2.png">
        </a> 
        <a class="btn-admin btn-floating waves-effect waves-light">
            <img src="img/3.png">
        </a>
        <a class="btn-admin btn-floating waves-effect waves-light">
            <img src="img/4.png">
        </a> 
        <a class="btn-admin btn-floating waves-effect waves-light">
            <img src="img/5.png">
        </a>
    </div>
</div>