<nav>
    <div class="nav-wrapper">
        <a href="<?php echo site_url()?>" class="brand-logo">MiResto</a>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
            <li><a href="<?php echo site_url()?>/nosotros">Nosotros</a></li>
            <li><a href="<?php echo site_url()?>/competencia">Competencia</a></li>
            <li><a href="<?php echo site_url()?>/webresto">Mi Resto 2.0</a></li>
        </ul>
        <ul class="side-nav" id="mobile-demo">
            <li><a href="<?php echo site_url()?>/nosotros">Nosotros</a></li>
            <li><a href="<?php echo site_url()?>/competencia">Competencia</a></li>
            <li><a href="<?php echo site_url()?>/webresto">Mi Resto 2.0</a></li>
         </ul>   
    </div>
</nav>