<footer class="fondo-barra page-footer">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">Bohemia - Resto & Bar - Bahía Blanca.</h5>
                <p class="grey-text text-lighten-4">
                Fundada en el año 1916, mantiene su liderazgo a nivel gastronómico en la ciudad. Familia de dueños que garantizan
                calidad y excelencia, porque durante #100Años, nuestros clientes lo retratan. 
                ¡Te esperamos! #Bohemia100Años.
                </p>
            </div>
            <div class="col l4 offset-l2 s12">
                <ul>
                    <li><a class="grey-text text-lighten-3" href="http://www.facebook.com/Bohemia-resto-bar" target="_blank">Facebook</a></li>
                    <li><a class="grey-text text-lighten-3" href="http://www.twitter.com/Bohemia-resto-bar" target="_blank">Twitter</a></li>
                    <li><a class="grey-text text-lighten-3" href="http://www.jg-design.com.ar" target="_blank">Desarrolladores</a></li>
                </ul>
            </div>
        </div>
</div>
<div class="footer-copyright">
    <div class="container"> Bohemia © 2016 Copyright - Todos los derechos reservados </div>
</div>
</footer>