<footer class="page-footer">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
            </div>
            <div class="col l4 offset-l2 s12">
                <ul>
                    <li><a class="grey-text text-lighten-3" href="http://www.facebook.com/miResto">Facebook</a></li>
                    <li><a class="grey-text text-lighten-3" href="http://www.twitter.com/miResto">Twitter</a></li>
                    <li><a class="grey-text text-lighten-3" href="http://www.cs.uns.edu.ar">Desarrolladores</a></li>
                </ul>
            </div>
        </div>
</div>
<div class="footer-copyright">
    <div class="container"> © 2014 Copyright - Todos los derechos reservados </div>
</div>
</footer>