<script src="<?php echo site_url() ?>js/jquery-2.2.0.min.js" type="text/javascript"></script>
<script src="<?php echo site_url() ?>js/jquery-ui.min.js" type="text/javascript"></script>
<script src="<?php echo site_url() ?>js/materialize.js" type="text/javascript"></script>
<script src="<?php echo site_url() ?>js/animaciones.js" type="text/javascript"></script>
<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="<?php echo site_url() ?>css/jquery-ui.min.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo site_url() ?>css/materialize.min.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo site_url() ?>css/Estilo.css" rel="stylesheet" type="text/css"/>
