<div class="row">
    <form class="col s12">
        <div class="row">
          <div class="input-field col s4">
            <input placeholder="Nombre" id="nombre" type="text" class="validate">
            <label for="nombre">Nombre</label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s4">
            <input placeholder="Direccion" id="direccion" type="text" class="validate">
            <label for="direccion">Direccion</label>
          </div>
          <div class="input-field col s4">
              <input placeholder="DNI"id="dni" type="text" class="validate">
            <label for="dni">DNI</label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s3">
            <input placeholder="Telefono" id="telefono" type="text" class="validate">
            <label for="telefono">Telefono</label>
          </div>
          <div class="input-field col s3">
              <input placeholder="Email"id="email" type="text" class="validate">
            <label for="email">Email</label>
          </div>
          <div class="input-field col s2">
              <input placeholder="Cuit" id="cuit" type="text" class="validate">
            <label for="cuit">Cuit</label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s4">
            <input placeholder="Password" id="password" type="text" class="validate">
            <label for="password">Password</label>
        </div>
        <div class="row">
            <div class = " col s4 ">
                <?php foreach ($roles as $rol){?>
                <input type="checkbox" value="<?php echo $rol ?>"                
                <?php }?>
            </div>
        </div>
        
        <button class="btn waves-effect waves-light" type="submit" name="action">
            Aceptar <i class="material-icons right">send</i>
        </button>
        <a href ="<?php echo  site_url()?>empleados/abmEmpleado" class="btn waves-effect waves-light">Salir</a>
    </form>
  </div>