<div class="row">
    <div class="col s12 center-align">
        <h3>Esto seria la sección de empleados. Se muestran en tabs todos los roles disponibles
        para un dado usuario. </h3>
    </div>
</div>

<div class="row">
    <div class="col s12">
        <ul class="tabs">
            <?php foreach ($roles as $rol){ ?>
                <li class="tab col s2"><a href="#<?php echo $rol ?>"><?php echo $rol ?></a></li>
            <?php } ?>
        </ul>
    </div>
    <?php foreach ($roles as $rol){
        include 'roles/'.$rol.'/cp.phtml';
    }
?>
</div>