<div class="row txt-cabecera">
    EMPLEADOS
</div>
<div class="row txt-info">
    ..: Listando los empleados existentes :..
</div>
<div class="row center-align">
    <a class="btn waves-effect waves-light" href="<?php echo site_url()?>empleados/alta">Agregar Empleado</a>
</div>
<div class="row">
    <div class="col s12 m8 offset-m2">
        <table class="responsive-table highlight">
            <thead>
                <th>#ID</th>
                <th>DNI</th>
                <th>Nombre</th>
                <th>Acciones</th>
            </thead>
            <tbody>
            <?php foreach ($empleados as $empleado) { ?>
                <tr>
                    <td><?php echo $empleado['id']; ?></td>
                    <td><?php echo $empleado['dni']; ?></td>
                    <td><?php echo $empleado['nombre']; ?></td>
                    <td>
                        <a class="btn waves-effect waves-green" href="<?php echo site_url().'empleados/ver/'.$empleado['id']; ?>"><i class="material-icons">info</i></a>
                        <a class="btn waves-effect waves-green" href="<?php echo site_url().'empleados/editar/'.$empleado['id']; ?>"><i class="material-icons">edit</i></a>
                        <a class="dropdown-button btn" data-activates="<?php echo 'drop'.$empleado['id']; ?>" ><i class="material-icons">delete</i></a>
                        <ul id='<?php echo 'drop'.$empleado['id']; ?>' class='dropdown-content'>
                            <li>¿Confirma?</li>
                            <li class="divider"></li>
                            <li>
                                <a href="<?php echo site_url().'empleados/eliminar/'.$empleado['id']; ?>">Sí</a>
                            </li>
                            <li>
                                <a>No</a>
                            </li>
                        </ul>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>
