<div id="Admin">
    <div class="col s12 center-align">
        <div  class = "div-btn-rol col s4 m3">
            <a href="<?php echo site_url() ?>webresto/empleados/menu" >
                Menu
                <img  src="<?php echo site_url()?>img/1.png" class="btn-rol btn-floating waves-effect waves-light">
            </a>
        </div>
        <div class = "div-btn-rol col s4 m3">
            <a href="<?php echo site_url() ?>empleados/abmempleado" >
                Empleados
            <img src="<?php echo site_url()?>img/1.png" class="btn-rol btn-floating waves-effect waves-light">
            </a>
        </div>
        <div class = "div-btn-rol col s4 m3">
            <a href="<?php echo site_url() ?>empleados/">
            <img src="<?php echo site_url()?>img/2.png" class="btn-rol btn-floating waves-effect waves-light">
            </a>
        </div>
        <div class = "div-btn-rol col s4 m3">
            <a href="<?php echo site_url() ?>empleados/ " >
            <img src="<?php echo site_url()?>img/3.png" class="btn-rol btn-floating waves-effect waves-light">
            </a>
        </div>
        <div class = "div-btn-rol col s4 m3">
            <a href="<?php echo site_url() ?>empleados/ " >
                <img src="<?php echo site_url()?>img/4.png" class="btn-rol btn-floating waves-effect waves-light">
            </a>
        </div> 
         <div class = "div-btn-rol col s4 m3">
             <a href="<?php echo site_url() ?>webresto/logout " >
            Salir
            <img src="<?php echo site_url()?>img/4.png" class="btn-rol btn-floating waves-effect waves-light">
                    </a>
        </div>   
    </div>
</div>