<div class="txt-cabecera">
    MENÚES.
</div>
<div class="row center-align">
    <a class="btn waves-effect waves-green" onClick="menu.preAlta()" >AGREGAR MENU</a>
</div>
<div class="row">
    <div class="col m8 s12 offset-m2">
        <table class="responsive-table">
            <thead>
                <td>#ID</td>
                <td>Nombre</td>
                <td>Creador</td>
                <td>Acciones</td>
            </thead>
            <tbody id="tablaMenues">   
            <?php
                foreach( $menues as $row ){
                    $id = $row['id'];
                    $nm = $row['nombre_menu'];
                    $nc = $row['nombre_creador'];
            ?>
                <tr id="<?php echo 'fm'.$id; ?>">
                    <td><?php echo $id; ?></td>
                    <td><?php echo $nm; ?></td>
                    <td><?php echo $nc; ?></td>
                    <td> 
                        <a class="btn waves-effect waves-green" href="<?php echo site_url()."menu/ver/".$id; ?>"><i class="material-icons">info</i></a>
                        <a class="btn waves-effect waves-green" href="<?php echo site_url()."menu/editar/".$id; ?>"><i class="material-icons">edit</i></a>
                        <a class='dropdown-button btn' data-activates='<?php echo 'drop'.$id; ?>'><i class="material-icons">delete</i></a>
                        <!-- Dropdown Structure -->
                        <ul id='<?php echo 'drop'.$id; ?>' class='dropdown-content'>
                            <li>¿Confirma?</li>
                            <li class="divider"></li>
                            <li>
                                <a onClick="<?php echo "menu.eliminar(".$id.")"; ?>">Sí</a>
                            </li>
                            <li>
                                <a>No</a>
                            </li>
                        </ul>
                    </td>
                </tr>
            <?php
                }
            ?>
            </tbody>
        </table>
    </div>
</div>

<div id="altaMenu" class="modal">
    <div class="modal-content">
        <div class="row">
            <div class="input-field col s12">
                <input id="nombreMenu" placeholder="Ingrese nombre..." type="text">
                <label>Nombre</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12 m6">
                <select id="selectDia">
                    
                </select>
                <label>Seleccione Rest. Día...</label>
            </div>
            <div class="input-field col s12 m6">
                <select id="selectHora">
                    
                </select>
                <label>Seleccione Rest. Hora...</label>
            </div>
        </div>
        <div class="row center-align">
            <a class="btn" onClick="menu.postAlta()">Confirmar</a>
        </div>
    </div>
</div>
