<div class="txt-cabecera">
    Menúes actuales en miResto.
</div>
<div class="row">
    <div class="col m8 s12 offset-m2">
        <table class="responsive-table">
            <thead>
                <td>#ID</td>
                <td>Nombre</td>
                <td>Creador</td>
                <td>Acciones</td>
            </thead>
            <tbody>   
            <?php
                foreach( $menues as $row ){
                    $id = $row['id'];
                    $nm = $row['nombre_menu'];
                    $nc = $row['nombre_creador'];
            ?>
                <tr>
                    <td><?php echo $id; ?></td>
                    <td><?php echo $nm; ?></td>
                    <td><?php echo $nc; ?></td>
                    <td> 
                        <a class="btn waves-effect waves-green" href="<?php echo site_url()."menu/ver/".$id; ?>"><i class="material-icons">info</i></a>
                        <a class="btn waves-effect waves-green" href="<?php echo site_url()."menu/editar/".$id; ?>"><i class="material-icons">edit</i></a>
                        <a class='dropdown-button btn' data-activates='<?php echo 'drop'.$id; ?>'><i class="material-icons">delete</i></a>
                        <!-- Dropdown Structure -->
                        <ul id='<?php echo 'drop'.$id; ?>' class='dropdown-content'>
                            <li>¿Confirma?</li>
                            <li class="divider"></li>
                            <li>
                                <a href="<?php echo site_url()."menu/eliminar/".$id; ?>">Sí</a>
                            </li>
                            <li>
                                <a>No</a>
                            </li>
                        </ul>
                    </td>
                </tr>
            <?php
                }
            ?>
            </tbody>
        </table>
    </div>
</div>
