<div class="txt-cabecera">
    MENÚES
</div>
<div class="txt-info">
    ..: Info menú :..
</div>
<div class="row">
    <div class="col m10 s12 offset-m1">
        <ul class="collapsible" data-collapsible="accordion">
            <li> 
                <div class="collapsible-header">Datos generales</div>
                <div class="collapsible-body">
                    <div class="row">
                        <div class="input-field col s4 m1">
                            <input value="<?php echo $datos['id'];?>" type="text" readonly>
                            <label>ID Carta</label>
                        </div>
                        <div class="input-field col s8 m4">
                            <input value="<?php echo $datos['nombre_creador'];?>" type="text" readonly>
                            <label>Creador</label>
                        </div>
                        <div class="input-field col s12 m4">
                            <input value="<?php echo $datos['nombre_menu'];?>" type="text" readonly>
                            <label>Nombre menú</label>
                        </div>
                    </div>
                </div>
            </li> 
            <li> 
                <div class="collapsible-header">Restricción Horas</div>
                <div class="collapsible-body">
                    <div class="row">
                        <div class="input-field col s4 m1">
                            <input value="<?php echo $restricciones_hora['id'];?>" type="text" readonly>
                            <label>ID</label>
                        </div>
                        <div class="input-field col s8 m4">
                            <input value="<?php echo $restricciones_hora['nombre_creador'];?>" type="text" readonly>
                            <label>Creador</label>
                        </div>
                        <div class="input-field col s12 m4">
                            <input value="<?php echo $restricciones_hora['nombre_restriccion'];?>" type="text" readonly>
                            <label>Nombre restricción</label>
                        </div>
                    </div>
                    <div class="row">
                        <table class="responsive-table">
                            <thead>
                                <tr>
                                    <th>00</th><th>01</th><th>02</th><th>03</th><th>04</th><th>05</th>
                                    <th>06</th><th>07</th><th>08</th><th>09</th><th>10</th><th>11</th>
                                    <th>12</th><th>13</th><th>14</th><th>15</th><th>16</th><th>17</th>
                                    <th>18</th><th>19</th><th>20</th><th>21</th><th>22</th><th>23</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                <?php 
                                    for($i=0; $i<24; $i++){ 
                                        if ($restricciones_hora[$i] == FALSE){
                                            $icon = '<i class="material-icons">clear</i>';  
                                        }else{
                                            $icon = '<i class="material-icons">done</i>';
                                        }
                                        echo '<td> <a>'.$icon.'</a> </td>';
                                    }
                                ?>
                                </tr>
                            </tbody>
                        </table>
                    </div> 
                </div>
            </li> 
            <li> 
                <div class="collapsible-header">Restricción Días</div>
                <div class="collapsible-body">
                    <div class="row">
                        <div class="input-field col s4 m1">
                            <input value="<?php echo $restricciones_dia['id'];?>" type="text" readonly>
                            <label>ID</label>
                        </div>
                        <div class="input-field col s8 m4">
                            <input value="<?php echo $restricciones_dia['nombre_creador'];?>" type="text" readonly>
                            <label>Creador</label>
                        </div>
                        <div class="input-field col s12 m4">
                            <input value="<?php echo $restricciones_dia['nombre_restriccion'];?>" type="text" readonly>
                            <label>Nombre restricción</label>
                        </div>
                    </div>
                    <table class="responsive-table">
                        <thead>
                            <tr>
                                <th>Lun.</th><th>Mar.</th><th>Mier</th><th>Jue.</th>
                                <th>Vie.</th><th>Sáb.</th><th>Dom.</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                        <?php 
                            for($i=1; $i<8; $i++){ 
                                if ($restricciones_dia[$i % 6] == FALSE){
                                    $icon = '<i class="material-icons">clear</i>';  
                                }else{
                                    $icon = '<i class="material-icons">done</i>';
                                }
                                echo '<td> <a>'.$icon.'</a> </td>';
                            }  
                        ?>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </li> 
            <li> 
                <div class="collapsible-header">Productos</div>
                <div class="collapsible-body">
                    <table class="responsive-table">
                        <thead>
                            <tr>
                                <th>#ID</th>
                                <th>Seccion</th>
                                <th>Producto</th>
                                <th>Precio</th>
                                <th>Lista Precio</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php 
                            foreach($productos as $row){
                                $id = $row['id_producto'];
                                $ns = $row['seccion_nombre'];
                                $np = $row['nombre_producto'];
                                $nlp = $row['nombre_lista_precio'];
                                $p = $row['precio_producto'];
                        ?>
                            <tr>
                                <td><?php echo $id; ?></td>
                                <td><?php echo $ns; ?></td>
                                <td><?php echo $np; ?></td>
                                <td><?php echo $nlp; ?></td>
                                <td><?php echo '$'.$p; ?></td>
                            </tr>
                        <?php        
                            }
                        ?>
                        </tbody>
                    </table>
                </div>
            </li>
            <li> 
                <div class="collapsible-header">Promociones</div>
                <div class="collapsible-body">
                    <table class="responsive-table">
                        <thead>
                            <tr>
                                <th>#ID</th>
                                <th>Promoción</th>
                                <th>Precio</th>
                                <th>Info</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php 
                            foreach($promociones as $row){
                                $id = $row['id'];
                                $n = $row['nombre'];
                                $p = $row['precio'];
                        ?>
                            <tr>
                                <td><?php echo $id; ?></td>
                                <td><?php echo $n; ?></td>
                                <td><?php echo '$'.$p; ?></td>
                                <td>
                                    <a class="btn waves-effect waves-green" href="<?php echo site_url()."promociones/ver/".$id; ?>">
                                        <i class="material-icons">info</i>
                                    </a>
                                </td>
                            </tr>
                        <?php        
                            }
                        ?>
                        </tbody>
                    </table>
                </div>
            </li>
        </ul>
    </div>
</div>
<div class="row center-align">
    <a class="btn waves-effect waves-light tooltipped" data-tooltip="Volver a menu" href="<?php echo site_url()?>menu">Volver</a> 
</div>