<div class="row ">
    <?php $atrib = array("onsubmit"=>"return confirm('¿Realmente quiere editar este empleado?')");
          echo form_open('empleados/alta'); ?>
        <div class="row">
          <div class="input-field col s4">
            <input placeholder="Nombre" id="nombre" type="text" class="validate" name="nombre">
            <label for="nombre">Nombre</label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s4">
            <input placeholder="Direccion" id="direccion" type="text" class="validate" name="direccion">
            <label for="direccion">Direccion</label>
          </div>
          <div class="input-field col s4">
              <input placeholder="DNI"id="dni" type="text" class="validate" name="dni">
            <label for="dni">DNI</label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s3">
            <input placeholder="Telefono" id="telefono" type="text" class="validate" name="telefono">
            <label for="telefono">Telefono</label>
          </div>
          <div class="input-field col s3">
              <input placeholder="Email"id="email" type="text" class="validate" name="email">
            <label for="email">Email</label>
          </div>
          <div class="input-field col s2">
              <input placeholder="Cuit" id="cuit" type="text" class="validate" name="cuit">
            <label for="cuit">Cuit</label>
          </div>
        </div>
        <div class="row">
            <div class="input-field col s4">
               <input placeholder="Password" id="password" type="password" class="validate" name="password">
               <label for="password">Password</label>
            </div>
            <div class="input-field col s4">
               <input placeholder="Confirmar Password" id="passwordConf" type="password" class="validate" name="passwordConf">
               <label for="passwordConf">Confirmar Password</label>
            </div>
        </div>
        <div class="row left-align">
            <div class="col s4">
                <input id="admin" type="checkbox" name="data[]" value="1" >
                <label for="admin">Aministrador</label><br>
                <input id="gerente" type="checkbox" name="data[]" value="3">
                <label for="gerente">Gerente</label><br>
                <input id="cajero" type="checkbox" name="data[]" value="2">
                <label for="cajero">Cajero</label><br>
                <input id="mozo" type="checkbox" name="data[]" value="4">
                <label for="mozo">Mozo</label><br>
                <input id="cocinero" type="checkbox" name="data[]" value="5">
                <label for="cocinero">Cocinero</label><br>
                <input id="recepcionista" type="checkbox" name="data[]" value="6">
                <label for="recepcionista">Recepcionista</label>
            </div>
            <div class="col s4">
            <input type="submit" value="Aceptar" class="btn waves-effect waves-light"/>
            <a href ="<?php echo  site_url()?>empleados/abm" class="btn waves-effect waves-light">Salir</a>
             </div>
        </div>
        
    </form>
</div>