<div class ="row center-align col s12">
    
        <table class = "highlight centered responsive-table">
            <thead>
              <tr>
                  
                  <th data-field="dni">Dni</th>
                  <th data-field="nombre">Nombre</th>
                  <th data-field="direccion">Direccion</th>
                  <th data-field="telefono">Telefono</th>
                  <th data-field="email">Email</th>
                  <th data-field="cuit">Cuit</th>
                  <th></th>
              </tr>
            </thead>
            <tbody>
              <?php	foreach ($empleados as $empleado) { ?>
                <tr>
                    <td><?php echo $empleado['dni']; ?></td>
                    <td><?php echo $empleado['nombre']; ?></td>
                    <td><?php echo $empleado['direccion']; ?></td>
                    <td><?php echo $empleado['telefono']; ?></td>
                    <td><?php echo $empleado['email']; ?></td>
                    <td><?php echo $empleado['cuit']; ?></td>
                    <td><form name="tabla" action="<?php echo site_url() ?>empleados/editarEmpleado" method="POST">
                        <a href="<?php echo site_url()?>empleados/editarEmpleado"  >
                            <button class="btn waves-effect waves-light" type="submit" value="<?php echo $empleado['id']; ?>" name="editar">
                                    <i class="material-icons right">edit</i>
                            </button>
                        </a>
                        </form>
                    </td>
                    <td><form name="tabla" action="<?php echo site_url() ?>empleados/eliminarEmpleado" method="POST">
                        <a href="<?php echo site_url()?>empleados/principalABM"  >
                            <button class="btn waves-effect waves-light" type="submit" value="<?php echo $empleado['id']; ?>" name="eliminar">
                                    <i class="material-icons right">delete</i>
                            </button>
                        </a>
                        </form>
                    </td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
        <a href="<?php echo site_url()?>empleados/altaEmpleado" class="btn waves-effect waves-light">
            Agregar Empleado
        </a>
    
</div>