<div class="cuerpo-principal">
    <div class="slider">
        <ul class="slides">
            <li>
                <img class="img-slider" src="./img/Slide_messi.jpg"> <!-- random image -->
                <div class="caption right-align">
                    <h3>#NoTeVayasLio</h3>
                    <h5 class="light grey-text text-lighten-3">Bohemia te banca fuerte.</h5>
                </div>
            </li>
            <li>
                <img class="img-slider" src="<?php echo site_url().'img/Slide_hamburguesa.jpg'; ?>"> <!-- random image -->
                <div class="caption center-align">
                    <h3>#BohemiaYVos</h3>
                    <h5 class="light grey-text text-lighten-3">Comidas rápidas.</h5>
                </div>
            </li>
            <li>
                <img class="img-slider" src="<?php echo site_url().'img/Slide_coctel.jpg'; ?>"> <!-- random image -->
                <div class="caption right-align">
                    <h3>#BohemiaYVos</h3>
                    <h5 class="light grey-text text-lighten-3">Tragos. Eventos especiales.</h5>
                </div>
            </li>
            <li>
                <img class="img-slider"  src="<?php echo site_url().'img/Slide_asado.jpg'; ?>"> <!-- random image -->
                <div class="caption left-align">
                    <h3>#BohemiaYVos</h3>
                    <h5 class="light grey-text text-lighten-3">La opción del domingo.</h5>
                </div>
            </li>
            <li>
                <img class="img-slider"  src="<?php echo site_url().'img/Slide_coctel_1.jpg'; ?>"> <!-- random image -->
                <div class="caption left-align">
                    <h3>#BohemiaYVos</h3>
                    <h5 class="light grey-text text-lighten-3">After offices.</h5>
                </div>
            </li>
        </ul>
    </div>
</div>