<div class = "row">
    <div class ="col s3 m3 ">
    <ul class="collapsible" data-collapsible="accordion">
        <li>
            <!-- el green es por ahora, despues hay que agregar estilo, de acuerdo a como queramos -->
            <div class="green btn waves-light waves-effect btn-info-comp collapsible-header">Info Competencia</div>             
        </li>
        <li>
            <div class="green btn waves-light waves-effect collapsible-header">Rankings</div>
            <div class="collapsible-body">
                <ul class="collapsible" data-collapsible="accordion">
                  <li>
                    <div  class="green btn waves-light waves-effect btn-mundial collapsible-header">Mundial</div>
                  </li>
                  <li>
                    <div class="green btn waves-light waves-effect btn-nacional collapsible-header">Nacional</div>
                  </li>
                  <li>
                    <div class="green btn waves-light waves-effect btn-provincial collapsible-header">Provincial</div>
                  </li>
               </ul>
            </div>
        </li>
    </ul>
    </div>
    <div class="data-competencia col s9 m9 ">
        Aca iria la informacion, linkeada a los botones
    </div>
</div>
