<div class = "row competencia">
    <div class = "col s3 m3 ">
        <ul class="collapsible" data-collapsible="accordion">
            <li>
              <div class="collapsible-header"><i class="material-icons"></i>Info Competencia</div>
            </li>
            <li>
              <div class="collapsible-header"><i class="material-icons"></i>Ranking</div>
              <div class="collapsible-body">
                  <ul class="collapsible" data-collapsible="accordion">
                          <li><p>Mundial</p></li>
                          <li><p>Nacional</p></li>
                          <li><p>Regional</p></li>
                          <li><p>Local</p></li>
                  </ul>
              </div>
            </li>
            
        </ul>
    </div>
    <div class = "col s9 m9 ">
        <p>Texto de bienvenida, que aporta informacion acerca de que es la competencia.</p>
    </div>
</div>