<div class = "row">
    <div class ="col s3 m3 ">
    <ul class="collapsible" data-collapsible="accordion">
        <li>
            <!-- el green es por ahora, despues hay que agregar estilo, de acuerdo a como queramos -->
            <a href="<?php echo site_url() ?>competencia/index">
            <div class="green btn waves-light waves-effect btn-info-comp collapsible-header">Info Competencia</div> 
            </a>
        </li>
        <li>
            <div class="green btn waves-light waves-effect collapsible-header">Rankings</div>
            <div class="collapsible-body">
                <ul class="collapsible" data-collapsible="accordion">
                  <li>
                    <a href="<?php echo site_url() ?>competencia/mundial">
                        <div class="green btn waves-light waves-effect btn-mundial collapsible-header">
                            Mundial
                        </div>
                    </a>
                  </li>
                  <li>
                    <a href="<?php echo site_url() ?>competencia/nacional">
                        <div class="green btn waves-light waves-effect btn-nacional collapsible-header">
                            Nacional
                        </div>
                    </a>
                  </li>
                  <li>
                    <a href="<?php echo site_url() ?>competencia/provincial">
                        <div class="green btn waves-light waves-effect btn-provincial collapsible-header">
                            Provincial
                        </div>
                    </a>
                  </li>
               </ul>
            </div>
        </li>
    </ul>
    </div>
    
    
        
 
    

