<div class="row ">
    <?php 
        $attr = array('autocomplete' => 'off');
        echo form_open('mozo/abrirMesa', $attr); 
    ?>
        <div class="row">
            <div class="input-field col s4">
                <input placeholder="Codigo" id="codigo" type="text" class="validate" name="codigo">
                <label for="codigo">Codigo</label>
            </div>
        </div>
       <input type="hidden" name="editar" value="<?php echo $editar ?>"> 
        <div class="col s4">
            <input type="submit" value="Aceptar" class="btn waves-effect waves-light"/>
            <a href ="<?php echo  site_url()?>mozo/" class="btn waves-effect waves-light">Salir</a>
        </div>
    </div>
        
    </form>
</div>