 <script src="<?php echo site_url(); ?>js/mozo/controladorMesa.js" type="text/javascript"></script>
 <script src="<?php echo site_url(); ?>js/mozo/vistaMesa.js" type="text/javascript"></script>
<div class="txt-cabecera">
    Administración Mesa <?php echo $num_mesa ?>
</div>
 <input id="inputMesa" type="hidden" value="<?php echo $id_mesa?>">
<div class="row">
    <div class="col m8 s12 offset-m2">
        <ul class="tabs">
            <li class="tab"><a class="active" href="#vincular">VINCULAR</a></li>
            <li class="tab"><a href="#menu">MENU</a></li>
            <li class="tab"><a href="#pedidos" onclick="mozo_mesa_vista.listarCarrito()">PEDIDOS</a></li>  
        </ul>
    </div>
</div>


<div id="vincular" class="row">
    <div class="col m8 s12 offset-m2 ">
        <div class="row center-align">
            <div class="input-field col s4">
                <input id="inputCodigo" name="codigo" type="text" class="validate">
                <label for="inputCodigo">Codigo</label>
            </div>
        <div class="col s4">
            <a class='dropdown-button btn btn-adminmesa' href='#' data-activates='dropdown1'>Vincular</a>
            <ul id='dropdown1' class='dropdown-content '>
                                        <li>¿Confirma?</li>
                                        <li class="divider"></li>
                                        <li>
                                            <a onClick="mozo_mesa.vincularCliente()">Sí</a>
                                        </li>
                                        <li>
                                            <a>No</a>
                                        </li>
            </ul>
            
      
        </div>
        </div>
        <div class="row">
            <p id="not-vincular"> </p>
        </div>
        
        <div class="row center-align">
            <form name="tabla" action="<?php echo site_url() ?>mesas/cerrar" method="POST">
            <a href="<?php echo site_url()?>mesas/cerrar">
                <button id="id_mesa" class="btn waves-effect waves-light" type="submit" value="<?php echo $id_mesa; ?>" name="id_mesa">
                    Cerrar Mesa
                </button>
            </a>
        </form>
            </div>
    </div>
</div>

<div id="menu" class="row">
    <div class="col m8 s12 offset-m2">
        <?php echo 'La carta actual es: '.$nombre_carta.'<br>'; ?>
        <ul class="collapsible" data-collapsible="accordion">
            <?php 
                $indice = 0;
                $cantidad = count($info_carta);
                while($indice<$cantidad){
                    $seccion_anterior = $info_carta[$indice]['nombre_seccion'];
                ?>
                    <!-- imprimo el encabezado y el tag para abrir el cuerpo del tab -->
                    <li> 
                        <div class="collapsible-header"> <?php echo $seccion_anterior; ?> </div>
                        <div class="collapsible-body">
                            <table class="responsive-table">
                            <tbody>          
                            <?php
                                //Mientras no cambie de encabezado, imprimo los elementos dentro
                                while($indice<$cantidad && $seccion_anterior === $info_carta[$indice]['nombre_seccion']){
                                    $row = $info_carta[$indice++];
                                    $np = $row['nombre_producto'];
                                    $id = $row['id_producto'];
                                    $p = $row['precio'];
                                    $id_lp = $row['id_lista_precio'];
                            ?>
                                <tr>
                                    <td> <img src="<?php echo site_url().'img/comidas/'.$id.'.png'; ?>"/> </td>
                                    <td><?php echo $np; ?></td>
                                    <td><?php echo '$'.$p; ?></td>
                                    <td> 
                                        <a class="btn waves-effect waves-green" onclick="<?php echo "mozo_mesa.producto.agregar(".$id.",'".$np."',".$p.",".$id_lp." )"; ?>"><i class="material-icons">add</i></a>
                                    </td>
                                </tr>
                            <?php
                                }
                            ?>
                            </tbody>
                            </table>
                        </div>
                    </li> 
                    
            <?php 
                }

                $indice = 0;
                $cantidad = count($info_promociones);
                while($indice<$cantidad){
                    $promo_anterior = $info_promociones[$indice]['nombre_promocion'];
                ?>
                    <li> 
                        <div class="collapsible-header"> <?php echo $promo_anterior; ?> </div>
                        <div class="collapsible-body">
                            <?php
                                $id_promo = $info_promociones[$indice]['id_promocion'];
                                $precio_promo = $info_promociones[$indice]['precio'];
                                $nom_promo = $info_promociones[$indice]['nombre_promocion'];
                            ?>
                            <div class="row">
                                <div class="input-field col s8 m1 offset-m5">
                                    <input value="<?php echo '$'.$precio_promo; ?>" type="text" readonly>
                                    <label>Costo</label>
                                </div>
                                <a class="input-field col s2 m1 btn" onclick="<?php echo "mozo_mesa.promocion.agregar(".$id_promo.",'".$nom_promo."',".$precio_promo.")"; ?>">
                                    <i class="material-icons">add</i>
                                </a>
                            </div>
                            <div class="row">
                                <table class="responsive-table">
                                <tbody>  
                                <?php
                                    //Mientras no cambie de encabezado, imprimo los elementos dentro
                                    while($indice<$cantidad && $promo_anterior === $info_promociones[$indice]['nombre_promocion']){
                                        $row = $info_promociones[$indice++];
                                        $np = $row['nombre_producto'];
                                        $id = $row['id_producto'];
                                ?>
                                    <tr>
                                        <td> <img src="<?php echo site_url().'img/comidas/'.$id.'.png'; ?>"/> </td>
                                        <td><?php echo $np; ?></td>
                                    </tr>
                                <?php
                                    }
                                ?>
                                </tbody>
                                </table>
                            </div>
                        </div>
                    </li> 
            <?php       
                }
            ?>
        </ul>
    </div>
</div>
    
<div id="pedidos" class="row">
    <div class="col m8 s12 offset-m2">
        <ul class="collapsible" data-collapsible="accordion">
            <li> 
                <div class="collapsible-header">Sin Confirmar</div>
                <div class="collapsible-body">
                    <div class="row center-align">
                        <a class="btn waves-effect" onclick="mozo_mesa.confirmar_pedido()">Confirmar pedidos</a>
                        <a class="btn waves-effect" onclick="mozo_mesa.vaciar_carrito()">Vaciar carrito</a>
                    </div>
                    <table class="responsive-table">
                        <tbody id="tablaCarrito">  
                        </tbody>     
                    </table>
                </div>
            </li>
            <li> 
                <div class="collapsible-header">Confirmados</div>
                <div class="collapsible-body">
                    <table class="responsive-table">
                        <thead>
                          <tr>
                              <th data-field="pedidor">Pedidor</th>
                              <th data-field="producto">Producto</th>
                              <th data-field="precio">Precio</th>
                              <th data-field="estado">Estado</th>
                          </tr>
                        </thead>
                        <tbody id="tablaConfirmados">
                            <?php
                                function calcularEstado($p,$s){
                                    if($s===NULL){
                                        if($p===NULL){
                                            $salida = 'Procesando...';
                                        }else{
                                            $salida = 'En cocina...';
                                        }
                                    }else{
                                        $salida = 'Para entregar...';
                                    }
                                    return $salida;
                                }
                                
                                foreach($pedidos_procesados as $row){
                                    $id_pedidor = $row['id_pedidor'];
                                    $pedidor = $row['nombre_pedidor'];
                                    $producto = $row['nombre_producto'];
                                    $precio = $row['precio'];
                                    $estado = calcularEstado($row['fecha_p'], $row['fecha_s']);
                            ?>
                                    <tr>
                                        <td><?php echo $id_pedidor.' | '.$pedidor; ?></td>
                                        <td><?php echo $producto; ?></td>
                                        <td><?php echo '$'.$precio; ?></td>
                                        <td><?php echo $estado; ?></td>
                                    </tr>
                            <?php
                                }
                                
                                foreach($promociones_procesadas as $row){
                                    $id_pedidor = $row['id_pedidor'];
                                    $pedidor = $row['nombre_pedidor'];
                                    $producto = $row['nombre_promocion'];
                                    $precio = $row['precio'];
                                    $estado = calcularEstado($row['fecha_p'], $row['fecha_s']);
                            ?>
                                    <tr>
                                        <td><?php echo $id_pedidor.' | '.$pedidor; ?></td>
                                        <td><?php echo $producto; ?></td>
                                        <td><?php echo '$'.$precio; ?></td>
                                        <td><?php echo $estado; ?></td>
                                    </tr>
                            <?php
                                }
                            ?>
                        </tbody>
                    </table>
                </div>
            </li>
        </ul>
    </div>  
</div>
<div class="row center-align">
<div class="col s12">
         <a href ="<?php echo  site_url()?>mozo/" class="btn-adminmesa btn waves-effect waves-light">Volver</a>
    </div>
</div>
<!-- Modal Structure -->
<div id="modalComentarios" class="modal">
    <div class="modal-content">
        <h4>Agregando Comentario</h4>
        <input id="inputComentario" type="text" maxlength="85" autocomplete="off">
    </div>
    <div class="modal-footer">
        <a onClick="mozo_mesa.enviarComentario()" class=" modal-action modal-close waves-effect waves-green btn-flat">OK</a>
    </div>
</div>