<div class =" row">
    <table class = "striped responsive-table">
        <thead>
          <tr>
              <th data-field="numeroMesa">Numero de Mesa</th>
              <th data-field="mozo">Mozo a cargo</th>
          </tr>
        </thead>
        <tbody>
           <?php foreach ($mesas as $mesa){?>
          <tr>
            <td><?php echo $mesa['numero'] ?></td>
            <td><?php echo $mesa['nombre'] ?></td>
          </tr>
           <?php } ?>
        </tbody>
    </table>
    <a href ="<?php echo  site_url()?>mozo/abrirMesa" class="btn waves-effect waves-light">Abrir Mesa</a>
    <a href ="<?php echo  site_url()?>webresto/" class="btn waves-effect waves-light">Volver</a>
    
</div>