<div id="Cocinero">
    <div class="col s12 center-align">
        <div  class = "div-btn-opc col s4 m3">
            <a href="<?php echo site_url() ?>empleados/pedidos" >
               Pedidos
                <img  src="<?php echo site_url()?>img/1.png" class="btn-opc btn-floating waves-effect waves-light">
            </a>
        </div>
        <div class = "div-btn-opc col s4 m3">
            <a href="<?php echo site_url() ?>empleados/pedidospentientes" >
            Pedidos Pendientes
            <img src="<?php echo site_url()?>img/1.png" class="btn-opc btn-floating waves-effect waves-light">
            </a>
        </div> 
        <div class = "div-btn-opc col s4 m3">
             <a href="<?php echo site_url() ?>webresto/logout ">
            Salir
            <img src="<?php echo site_url()?>img/4.png"  class="btn-opc btn-floating waves-effect waves-light">
                    </a>
        </div>   
    </div>
</div>