<div id="Recepcionista">
      <div class="col s12 center-align">
        <div  class = "div-btn-rol col s4 m3">
            <a href="<?php echo site_url() ?>webresto/empleados/Reservas" class="btn-rol btn-floating waves-effect waves-light">
               Reservas
                <img  src="<?php echo site_url()?>img/1.png">
            </a>
        </div>
        <div class = "div-btn-rol col s4 m3">
            <a href="<?php echo site_url() ?>webresto/empleados/mesas" class="btn-rol btn-floating waves-effect waves-light">
            Mesas
            <img src="<?php echo site_url()?>img/1.png">
            </a>
        </div>
        <div class = "div-btn-rol col s4 m3">
            <a href="<?php echo site_url() ?>webresto/ " class="btn-rol btn-floating waves-effect waves-light">
               Salir
               <img src="<?php echo site_url()?>img/4.png">
            </a>
        </div>   
    </div>
</div>