<div id="Recepcionista">
      <div class="col s12 center-align">
        <div  class = "div-btn-rol col s4 m3">
            <a href="<?php echo site_url() ?>webresto/empleados/Reservas" >
               Reservas
                <img  src="<?php echo site_url()?>img/1.png" class="btn-rol btn-floating waves-effect waves-light">
            </a>
        </div>
        <div class = "div-btn-rol col s4 m3">
            <a href="<?php echo site_url() ?>webresto/empleados/mesas" >
            Mesas
            <img src="<?php echo site_url()?>img/1.png" class="btn-rol btn-floating waves-effect waves-light">
            </a>
        </div>
        <div class = "div-btn-rol col s4 m3">
            <a href="<?php echo site_url() ?>webresto/ " >
               Salir
               <img src="<?php echo site_url()?>img/4.png" class="btn-rol btn-floating waves-effect waves-light">
            </a>
        </div>   
    </div>
</div>